# Generated by Django 4.2 on 2024-05-09 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("songs", "0005_alter_songscore_img_delete_songgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "songs",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="songs.song"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEventStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declaration",
                    models.CharField(
                        choices=[
                            ("Going", "Going to attend"),
                            ("Cant", "Can't attend"),
                            ("Undecided", "Don't know"),
                            ("Undeclared", "Not declared"),
                        ],
                        default="Undeclared",
                        max_length=20,
                        verbose_name="Attendance declaration",
                    ),
                ),
                (
                    "actual_attendance",
                    models.CharField(
                        blank=True,
                        choices=[("Present", "Attended"), ("Absent", "Didn't attend")],
                        max_length=20,
                        null=True,
                        verbose_name="Actual attendance",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statuses",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "event")},
            },
        ),
    ]
