# Generated by Django 4.2 on 2024-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songgroup",
            name="songs",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="song_groups", to="songs.song"
            ),
        ),
    ]
