# Generated by Django 4.2 on 2024-04-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_alter_songgroup_songs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songgroup",
            name="songs",
            field=models.ManyToManyField(
                blank=True, related_name="song_groups", to="songs.song"
            ),
        ),
    ]
