# Generated by Django 4.2 on 2024-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_alter_songgroup_songs"),
    ]

    operations = [
        migrations.AddField(
            model_name="songscore",
            name="img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
