# Generated by Django 4.2 on 2024-05-09 19:29

from django.db import migrations, models
import songs.models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0004_songscore_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songscore",
            name="img",
            field=models.ImageField(
                blank=True, upload_to=songs.models.song_directory_path
            ),
        ),
        migrations.DeleteModel(
            name="SongGroup",
        ),
    ]
