# Generated by Django 4.2 on 2024-05-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0006_alter_songscore_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songscore",
            name="song",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score",
                to="songs.song",
            ),
        ),
    ]
