# Generated by Django 4.2 on 2025-04-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='external_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
