# Generated by Django 4.2 on 2024-05-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("songs", "0005_alter_songscore_img_delete_songgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "songs",
                    models.ManyToManyField(
                        blank=True, related_name="song_groups", to="songs.song"
                    ),
                ),
            ],
        ),
    ]
