from django.db import models
from django.conf import settings
from django.core.validators import FileExtensionValidator

# used for converting pdf to image
from pdf2image import convert_from_bytes
from django.core.files import File
from io import BytesIO

class Song(models.Model):
    '''
    Model for songs.
    Each song has a title and a score (PDF and autogenerated image)
    and can have multiple recordings (MP3).
    '''
    title = models.CharField(max_length=255)
    # TODO add owner and choir fields once those apps are working
    # owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='songs')
    # choir = models.ForeignKey(Choir, on_delete=models.CASCADE, related_name='songs')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

def song_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/songs/<song.title>/<filename>
    return f'songs/{instance.song.title}/{filename}'

class SongScore(models.Model):
    '''
    Model for scores of songs.
    Each score has a user-uploaded pdf file
    and an image representation of the score autogenerated from the pdf during save.
    The image is used as a thumbnail for the score.
    '''
    song = models.OneToOneField(Song, on_delete=models.CASCADE, related_name='score')
    # TODO add user folders once user auth is implemented
    # TODO add a custom validator to ensure that the file is a PDF (not just using extensions)
    file = models.FileField(upload_to=song_directory_path, validators=[FileExtensionValidator( ['pdf'] ) ])
    img = models.ImageField(upload_to=song_directory_path, blank=True)  # image representation of the score

    def __str__(self):
        return f"{self.song.title} - score"

    # override the save method to create an image from the uploaded PDF
    def save(self, *args, **kwargs):
        self.img = create_img_from_pdf(self.file)  # create an image from the uploaded PDF file
        super().save(*args, **kwargs)  # Call the "real" save() method.


class SongRecording(models.Model):
    '''
    Model for recordings of songs.
    Or more specifically, recordings of a specific voice group of a song.
    Each song can have multiple recordings.
    Each recording has a user-uploaded mp3 file.
    '''
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name='recordings')
    voice_group = models.ForeignKey('VoiceGroup', on_delete=models.CASCADE, related_name='recordings', null=True)
    # TODO add support for wav files? (make sure that they're playable in browser)
    file = models.FileField(upload_to=song_directory_path, validators=[FileExtensionValidator( ['mp3', 'wav'] ) ])

    def __str__(self):
        return f"{self.song.title} - {self.voice_group} - recording"

class VoiceGroup(models.Model):
    '''
    Model for voice groups.
    Each voice group has a name (e.g., 'soprano', 'alto', 'tenor', men', 'group 1', 'all' etc.)
    A separate model is used so users can create their own, custom voice groups.
    '''
    name = models.CharField(max_length=50)  # e.g., 'soprano', 'alto', 'tenor', 'bass', 'men', 'women', 'group 1', 'group 2'

    def __str__(self):
        return self.name

### Helper functions ###
def create_img_from_pdf(pdf):
    """Creates an image of the first page of a pdf"""
    images = convert_from_bytes(pdf.read(), size=(550,None))  # holds all the pages as an array of Pil images
    img_io = BytesIO()  # needed as an intemediary to save the file from Pillow library
    images[0].save(img_io, "WEBP", quality=70)  # save image to BytesIO object
    img = File(img_io, name=pdf.name[:-4] + ".webp")  # create a django friendly File object
    return img
